version: "3.8" # docker-composeのバージョン選択
services:
  # サービス名
  node:
    # Dockerfileの設定
    build:
      context: . # Dockerfileがあるディレクトリ
      dockerfile: Dockerfile # Dockerfileの名前
    # データの永続化
    volumes:
      - ./:/app:cached # ホストのカレントディレクトリとコンテナ内の作業ディレクトリを同期
      - ./vuetify-project/node_modules:/app/vuetify-project/node_modules # 特定のパスを独立した名前付きボリュームとして定義
    environment:
      - HOST=0.0.0.0 # localhost接続をする際に必要
      - CHOKIDAR_USEPOLLING=true # ホットリロードを可能にする
    tty: true
    ports:
      - "3000:3000"
      - "4173:4173"
volumes:
  # 名前付きボリュームの設定
  node_modules:
